ppw_lab/urls.py
from django.contrib import admin
from django.urls import path, include
import story3.urls as story3

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story3', include(story3, namespace='story3')),
    path('', include(story3, namespace='story3'))
]

story3/urls.py
from django.urls import path
from .views import home, about, register

app_name = 'story3'
urlpatterns = [
    path('', home, name='home'),
    path('about', about, name='about'),
    path('register', register, name='register'),
    
]

story3/models.py
from django.db import models

# Create your models here.

story3/views.py
from django.shortcuts import render

# Create your views here.
def home (request):
    return render(request, 'Lab_3.html')

def about (request):
    return render (request, 'about.html')

def register (request):
    return render(request, 'register.html')

story3/templates/Lab_3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cardo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    {% load staticfiles %}
    <link rel='stylesheet' type="text/css href="{% static 'static/style.css' %}"   
    
    <style type="text/css">
    </style>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link href="css/animate.css" rel="stylesheet">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
    <title>Ikhsan's Website</title>

</head>


<body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#">SUN</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'story3:about' %}">About <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="#">Activity <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="#">Contact <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" style="font-weight: bold;" href="{% url 'story3:register' %}">REGISTER <span class="sr-only">(current)</span></a>
                    </li>
                    
                  </ul>
                  
                </div>
              </nav>

              <div class="header">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="header-left">
                                <img src="http://www.fourgeek.com/img/logo/logo.png" class="logo" alt="Logo">
                            </div>
                            <div class="top-title">
                                <h1 class="animated infinite bounceInDown">you’ll look
                                better with us</h1>
                                <h6 class="logo-title animated pulse">Co-operation is the best solution</h6>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="menu">
                                <li class="f-item-1"><a href="mh-1">Services</a></li>
                                <li class="f-item-2"><a href="mh-2">Works</a></li>
                                <li class="f-item-3"><a href="mh-3">Teams</a></li>
                                <li class="f-item-4"><a href="mh-4">Blogs</a></li>
                                <li class="f-item-5"><a href="mh-5">Find Us</a></li>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <h1>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </h1>
            </div>
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
            <script>
                $(document).ready(function(){
                    $( ".f-item-1" ).hover(function() {
                        $('.menu').css("background-color", "#8165a6");
                        }, function(){
                        $('.menu').css("background-color", "#d83f87");
                        });
                    // f-item-2
                    $( ".f-item-2" ).hover(function() {
                        $('.menu').css("background-color", "#735ed5");
                        }, function(){
                        $('.menu').css("background-color", "#d83f87");
                        });
                    // f-item-3
                    $( ".f-item-3" ).hover(function() {
                        $('.menu').css("background-color", "#797b7b");
                        }, function(){
                        $('.menu').css("background-color", "#d83f87");
                    });
                    // f-item-4
                    $( ".f-item-4" ).hover(function() {
                        $('.menu').css("background-color", "#1ea2e0");
                        }, function(){
                        $('.menu').css("background-color", "#d83f87");
                    });
                    // f-item-5
                    $( ".f-item-5" ).hover(function() {
                        $('.menu').css("background-color", "#4a90e2");
                        }, function(){
                        $('.menu').css("background-color", "#d83f87");
                    });
                });
            </script>
            <script>
            $(window).scroll(function() {
            var scroll = $(window).scrollTop();
            if (scroll >=50) {
            $(".header").addClass("myheader");
            } else {
            $(".header").removeClass("myheader");
            }
                });
            </script>

    <div class="atas">
        <img src = "{% static 'image\background.jpg' %}" id="background">
        
        <div class ="hijau">
            
            <div class="profile">
                <img src = "{% static 'image\ikhsan.jpg' %}" id="profile">
            </div>

            <div class="bio">
                <p id="nama">Ikhsanul Akbar Rasyid</p>
                <p>Medan, 5 May 1999</p>
                <p>Student in University of Indonesia</p>
                <p>ikhsanul.akbar@ui.ac.id</p>
            </div>

        </div>
        
    </div>

    

        <div class="container">
            <div class="row">
                <div class="sect1">
                    <h1 id = "heading1">About</h1>
                    <h2 id = "heading2">Me</h2>
                </div>

                <div class="col">
                    <p id="life">
                        I am a long-life learner. I believe that happines is everyone's right<br>
                        So, I always try to share it to thems ^^<br>
                        Now officially living in UI's dormitory #RumahBhinneka<br>
                        On progress to find my "identity"
                    </p>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                      
                    <div class="container">
                    <div class="row">
                        <div class="col-sm-9">
                            <h1>Organization</h1>
                            <p id="organ">
                                <div class="col-sm-12">
                                    <img src="{% static 'image\sa.jpg' %}" id="SA" width="100" height="100">
                                    <p id="SA">Place for sharing the happiness arround the dormitory, which is occupied by student from over this country, with varietive faculty</p>
                                </div>
                                <div class="col-sm-12">
                                    <img src="{% static 'image\fuki.jpg' %}" id="fuki" width="100" height="100">
                                    <p id="fuki">Place for learning and knowing friends in this beloved Fasilkom UI</p>
                                </div>
                            <p>
                        </div>
                        <div class="col-sm-3">
                            <h1>Education</h1>
                            <p id="edu">
                                <br>
                                2017 - ...<br>
                                University of Indonesia, West Java<br>
                                Computer Science Program<br>
                                GPA : 3.53/4.00<br>
                                <br>
                                2014 - 2017<br>
                                MAN 3 Malang, East Java
                            <p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
            
    </div>
    
</body>
</html>

story3/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style type="text/css">
        body {
            background-color:#C1C0FF;
        }
        #back {
            opacity: 0.75;
        }

        div.more h1 {
            position: absolute;
            text-align: center;
            margin-top: -20%;
            margin-left: 35%;
            font-weight: bold;
            font-family: 'Berkshire Swash', cursive;
            font-size: 50px;

        }

        #back {
            width: 1300px;
            height: 480px;
        }

        #skill {
            position: absolute;
            text-align: center;
            left: 40%;
            top: 70%;
            font-family: 'Berkshire Swash', cursive;
            font-size: 36px;
        }
    </style>

    <meta charset="UTF-8">
    <title>More About Me</title>

</head>

<body>
    <div class="atas">
        <img id="back" src="https://wallpapertag.com/wallpaper/full/e/d/0/119843-future-wallpaper-1920x1080-tablet.jpg">
        <div class="more">
            <h1>More About Me</h1>
        </div>
        
    </div>

    

    <div class="container-fluid">

    <div class="row">
        <div class="col-sm-4">
    	    <h1 id="skill">
                Skill
            </h1>
        </div>
    
    <div class="col-sm-8" style="background-color:lavenderblush;">
            <div class="container">
                    <p>Python</p>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:50%">
                        <span class="sr-only">30% Complete</span>
                      </div>
                    </div>
                  </div>

                  <div class="container">
                        <p>Java</p>
                        <div class="progress">
                          <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:35%">
                            <span class="sr-only">30% Complete</span>
                          </div>
                        </div>
                      </div>

                      <div class="container">
                            <p>HTML/CSS</p>
                            <div class="progress">
                              <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:10%">
                                <span class="sr-only">30% Complete</span>
                              </div>
                            </div>
                          </div>

                          <div class="container">
                                <p>Mathematical Problem Solving</p>
                                <div class="progress">
                                  <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:60%">
                                    <span class="sr-only">30% Complete</span>
                                  </div>
                                </div>
                              </div>
    </div>
  </div>
</div>

<br>
<br>
<div class="container-fluid">

        <div class="row">
            <div class="col-sm-4">
                <h1 id="skill">
                    <br>Language
                </h1>
            </div>
        
        <div class="col-sm-8" style="background-color:lavenderblush;">
                <div class="container">
                        <p>English</p>
                        <div class="progress">
                          <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:40%">
                            <span class="sr-only">30% Complete</span>
                          </div>
                        </div>
                      </div>
    
                      <div class="container">
                            <p>Arabic</p>
                            <div class="progress">
                              <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:25%">
                                <span class="sr-only">30% Complete</span>
                              </div>
                            </div>
                          </div>
    
                          <div class="container">
                                <p>Bahasa</p>
                                <div class="progress">
                                  <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:65%">
                                    <span class="sr-only">30% Complete</span>
                                  </div>
                                </div>
                              </div>
        </div>
      </div>
    </div>

</body>

</html>

story3/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style type="text/css">
        body {
            background-color:#C1C0FF;
        }
        
    </style>

    <meta charset="UTF-8">
    <title>Registration Form</title>

</head>

<body>

    <div class="container">
            <h2>Registration Form</h2>
            <form action="/action_page.php">
        
                <div class="form-group">
                    <label for="name">Name :</label>
                    <input type="name" class="form-control" id="name" placeholder="Enter name" name="name">
                </div>

                <div class="form-group">
                    <label for="date">Date of Birth :</label>
                    <input type="date" class="form-control" id="date" placeholder="Enter date of birth" name="date">
                </div>
                
                <div class="form-group">
                    <label for="email">Email :</label>
                    <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
                </div>

                <div class="form-group">
                    <label for="username">Username :</label>
                    <input type="username" class="form-control" id="username" placeholder="Enter username" name="username">
                </div>
              
                <div class="form-group">
                    <label for="pwd">Password :</label>
                    <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pwd">
                </div>

                <div class="form-group">
                    <label for="pwd">Password Confirmation :</label>
                    <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pwd">
                </div>

                <div class="checkbox">
                    <label><input type="checkbox" name="remember"> Remember me</label>
                </div>
                
                <button type="submit" class="btn btn-default">Submit</button>
            </form>

          </div>

</body>

</html>